### ISSUE TITLE
Suggestion: Dismiss Messages

### ISSUE THREAD

**Issue by Webmetz** [Stalruth/SableyeBot4#2]
Have a commands which allows Moderators to clear sableeye bot messages from the channel
`dismissall`

Allow the person who requested a message (or moderator) to react with a ❌ in order to dismiss a sableeye message.

**Comment by Stalruth** [comment]
Thanks for the suggestion!

I won't be implementing the first suggestion is something a moderation bot can do.

I won't be implementing the second because moderators can already delete messages which creates an Audit Log entry for others' information, and if a user doesn't want the output shown to others they can DM the bot.
